### ISSUE TITLE
CSS篇

### ISSUE THREAD

**Issue by zhongpeng** [zhongpeng/Blog#1]
# CSS相关面试题
#### CSS的基本语句构成是什么？

```
选择器｛属性1：值1；属性2：值2；.......｝
```
#### 设置DOMCSS样式样式？
- 外部样式表，引入一个外部CSS文件
- 内部样式表，将CSS代码放在<head>标签内部
- 内联样式，将css样式直接定义在HTML元素内部

<br/>
#### CSS选择器？
1. 派生选择器（用HTML标签申明）
2. ID选择器（用DOM的ID申明）
3. 类选择器（用一个样式名申明）
4. 属性选择器（用DOM的属性申明，属于CSS2，IE6不支持，不常用）
5. 后代选择器：父代名 后代名｛属性名：属性值｝
6. 子代选择器：父代名>子代名｛数姓名：属性值｝
7. 群组选择器：#name1，.name2,#name div{数姓名：属性值}
8. 伪类选择器：name:伪类
9. 通用（通配符）选择器：*｛属性名：属性值｝

<br/>
#### CSS选择器优先级怎么定义的？
- 一般而言，选择器越特殊，它的优先级越高。也就是选择器指向的越准确，它的优先级就越高。
- 复杂的计算方法
  - 用1表示派生选择器的优先级
  - 用10表示类选择器的优先级
  - 用100表示ID选择器的优先级
    - div.test1 .span var 优先级 1 + 10 + 10 +1
    - span#XXX .songs li 优先级 1+100+10+1
    - &nbsp;#XXX li 优先级 100+1
- 代码问题：
  
  ```
  <style>
      .classA{color:bule;}
      .classB{color:red;}
  </style>
  <body>
      <p class="classB classA">123</p>
  </body>
  ```
  
  上述代码P标签内的颜色是什么？
  答案：red。与样式定义在文件中的先后顺序有关，即是后面的覆盖前面的
  
  ```
  与在<p class="classB classA"> 中的先后关系无关
  ```

<br/>
#### CSS中可以通过哪些属性定义，使得一个DOM元素不显示在浏览器可视范围内？
- 最基本的：
  - 设置display属性为none，或者设置visibility属性为hidden
- 技巧性：
  - 设置宽高为0，设置透明度为0，设置z-index位置在-1000
#### 超链接访问过后hover样式就不出现的问题是什么？如何解决？
- 被点击访问过的超链接样式不在具有hover和active了,解决方法是改变CSS属性的排列
- 顺序: L-V-H-A（link,visited,hover,active）
#### 什么是CSS Hack？IE6、7、8的Hack分别是什么？
- 针对不同的浏览器写不同的CSS code的过程，就是CSS hack。
- IE6、7、8Hack设置：
  
  ```
  #test{   
      width:300px;   
      height:300px;   
      background-color:blue;      /*firefox*/
      background-color:red\9;     /*all ie*/
      background-color:yellow;    /*ie8*/
      +background-color:pink;     /*ie7*/
      _background-color:orange;   /*ie6*/
  }
  
  :root #test { background-color:purple\9; } /*ie9*/  
  
  /*opera*/
  @media all and (min-width:0px){ 
      #test {
          background-color:black;
      } 
  }  
  
  /*chrome and safari*/
  @media screen and (-webkit-min-device-pixel-ratio:0){ 
      #test {
          background-color:gray;
      } 
  }       
  ```

<br/>
#### 请用CSS写一个简单幻灯片效果页面

-使用animation动画实现一个简单的幻灯片效果

```
**HTML**/
    div.ani

/**css**/
    .ani{
      width:480px;
      height:320px;
      margin:50px auto;
      overflow: hidden;
      box-shadow:0 0 5px rgba(0,0,0,1);
      background-size: cover;
      background-position: center;
      -webkit-animation-name: "loops";
      -webkit-animation-duration: 20s;
      -webkit-animation-iteration-count: infinite;
    }
    @-webkit-keyframes "loops" {
        0% {
            background:url(xxxxx.jpg) no-repeat;             
        }
        25% {
            background:url(xxxxx.jpg) no-repeat;
        }
        50% {
            background:url(xxxxxx.jpg) no-repeat;
        }
        75% {
            background:url(xxxxxx.jpg) no-repeat;
        }
        100% {
            background:url(xxxxxxx.jpg) no-repeat;
        }
    }
```

<br/>
#### 行内元素,块级元素以及空元素有哪些？具体区别是什么？行内元素的padding和margin可设置吗？
- 行内元素：a、b、span、img、input、button、label、strong、select、textarea
- 块级元素：div、ul、li、dt、dd、p、h1-h6、
- 空元素：br、meta、hr、link、input、img
- 块级元素（Block）特性：
  - 总是独占一行，表现为另起一行开始，而且其后的元素也必须另起一行显示；
  - 宽度(width),高度(height),内边距(padding)和外边距(margin)都可控制
- 内联元素（inline）特性:
  - 和相邻的内联元素在同一行
  - 宽度(width),高度(height),内边距的top/bottom(padding-top/padding-bottom)和外边距的top/bottom(margin-top/margin-bottom)都不可改变（也就是padding和margin的left和right可以设置的），就是里面蚊子或图片的大小。
- 引申题：浏览器还有默认的天生inline-block元素（拥有内在尺寸、可设置高度、但不会自动换行），有哪些？
  - input
  - img
  - button
  - texterea
  - label

<br/>
#### 什么是外边距重叠？重叠的结果是什么？
- 外边距重叠就是margin-collapse
- 在CSS当中，相邻的两个盒子（可能是兄弟关系也可能是祖先关系）的外边距可以结合成一个单独的外边距。这种合并外边距的方式被称为折叠，并且因而所结合成的外边距称为折叠外边距。
- 折叠结果遵循下列计算规则：
  1. 两个相邻的外边距都是正数时，折叠结果是它们两者之间较大的值。
  2. 两个相邻的外边距都是负数时，折叠结果是两者绝对值的较大值。
  3. 两个外边距一正一负时，折叠结果是两者的相加的和。
     <br/>
#### rgba()和opacity的透明效果有什么不同？
- rgba()和opacity都能实现透明效果，但最大的不同是opacity作用于元素，以及元素内的所有内容的透明度，而rgba()只作用于元素的颜色或其背景色。（设置rgba透明的元素的子元素不会继承透明效果！）

<br/>
#### CSS中可以让文字垂直和水平方向上重叠的两个属性是什么？
- 垂直方向：line-height
- 水平方向：letter-spacing
- 引申问题：关于letter-spacing的妙用知道有哪些么？
  - 可以用于消除inline-block元素间的换行符空格间隙问题。

<br/>
#### 如何垂直居中一个浮动元素

```
// 方法一：已知元素的高宽
#div1{
    background-color:#6699FF;
    width:200px;
    height:200px;
    position: absolute;        //父元素需要相对定位
    top: 50%;
    left: 50%;
    margin-top:-100px ;   //二分之一的height，width
    margin-left: -100px;
}
//方法二:未知元素的高宽
#div1{
    width: 200px;
    height: 200px;
    background-color: #6699FF;
    margin:auto;
    position: absolute;        //父元素需要相对定位
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
}
```
- 引申问题：如何垂直居中一个img
  
  ```
  #container     //<img>的容器设置如下
  {
      display:table-cell;
      text-align:center;
      vertical-align:middle;
  }
  ```

<br/>
#### px和em的区别？PC端默认字体大小是多少？移动端默认字体大小是多少？如何修改浏览器默认字体大小？
- px和em都是长度单位，区别是，px的值是固定的，指定是多少就是多少，计算比较容易。em得值不是固定的，并且em会继承父级元素的字体大小。
- 浏览器的默认字体高都是16px。所以未经调整的浏览器都符合: 1em=16px。那么12px=0.75em, 10px=0.625em。

<br/>
#### Sass、Less是什么？大家为什么要使用他们？

<br/>
#### display:none与visibility:hidden的区别是什么？

<br/>
#### 说说你对于盒模型的理解

<br/>
#### 写出集中IE6 BUG的解决方法

<br/>
#### img标签上title与alt属性的区别是什么？

<br/>
#### 描述css reset的作用和用途

<br/>
#### 解释CSS Sprites，如何使用？

<br/>
#### 什么是浏览器标准模式？什么是怪异模式？两者的区别是什么？

<br/>

**Comment by zhongpeng** [comment]
测试测试
===========

**Comment by yechenfeng** [comment]
沙发
